# -*- coding: utf-8 -*-
"""Deployement Challenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yq9rlzelrcrwWwrXFvYgMpXfKK2cYy3D
"""

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
import joblib

data= pd.read_csv('bankloan.csv')
data.drop(["ID"], axis=1, inplace=True)
data

X = data.drop(columns=['Personal.Loan'])
y = data['Personal.Loan']
model = RandomForestClassifier()
model.fit(X,y)

joblib.dump(model, 'Classifier.pkl')

